name:                assert4hs-tasty
version:             0.0.0.1
github:              "paweln1986/assert4hs-tasty"
license:             MIT
author:              "Pawel Nosal"
maintainer:          "p.nosal1986@gmail.com"
copyright:           "2021 Pawel Nosal"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
synopsis:            Provider for tasty runner to run assert4hs tests
category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/paweln1986/assert4hs-tasty#readme>

dependencies:
- base >= 4.7 && < 5
- tasty
- assert4hs

ghc-options:
  - -haddock
  - -Wall
  - -Wcompat
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wredundant-constraints
  - -Wno-unused-do-bind
  - -Werror=incomplete-patterns

library:
  source-dirs: src

tests:
  assert4hs-tasty-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - assert4hs-tasty
